default:
 my_project:
  outputs:
    dev:
      type: snowflake
      account: pc.us.gcp
      database: dev_db
      warehouse: DEV_WAREHOUSE
      schema: "{{ env_var('USER', 'default_user') }}"
      authenticator: oauth
      oauth_client_id: [OAuth client id]
      oauth_client_secret: [OAuth client secret]
      token: [OAuth refresh token]
      threads: 4
    prod:
      type: snowflake
      account: pc.us.gcp
      user: "{{ env_var('SNOWFLAKE_USER') }}"  
      private_key_path: /path/to/snowflake_key.p8
      role: "{{ env_var('SNOWFLAKE_PROD_ROLE') }}"
      database: prod_db
      schema: prod
      warehouse: PROD_WAREHOUSE
      threads: 8
  target: dev
