default:
 bigquery:
  outputs:
    dev:
      type: bigquery 
      project: bigquery-project-id  # Development project
      dataset: hw_dev  # Development schema
      threads: 4
      method: oauth
      vars:
          user: "{{ env_var('USER', 'default_user') }}"
    prod:
      type: bigquery
      project: bigquery-project-id  # Production project
      dataset: hw_prod  # Production schema
      threads: 8
      method: oauth
  target: dev  # Default target
